#!/bin/bash
# =============================================================================
# generate_rpk_keys.sh - Generate ML-DSA-44 Raw Public Keys for DTLS 1.3
# =============================================================================
# This script generates ML-DSA-44 (Dilithium Level 2) keypairs and extracts
# the raw public keys in SubjectPublicKeyInfo format for use with wolfSSL's
# Raw Public Key (RPK) authentication (RFC 7250).
#
# Output files:
#   - client_key.pem      : Client ML-DSA-44 private key
#   - server_key.pem      : Server ML-DSA-44 private key
#   - client_pubkey.der   : Client public key (SubjectPublicKeyInfo DER)
#   - server_pubkey.der   : Server public key (SubjectPublicKeyInfo DER)
#   - client_rpk.h        : Header with client private key + server public key
#   - server_rpk.h        : Header with server private key + client public key
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "============================================================================="
echo "       ML-DSA-44 Raw Public Key (RPK) Generation for PQC-DTLS 1.3"
echo "============================================================================="
echo ""

# Check OpenSSL version and ML-DSA support
echo "[CHECK] Verifying OpenSSL ML-DSA-44 support..."
if ! openssl list -signature-algorithms 2>/dev/null | grep -q "ML-DSA-44"; then
    echo "[ERROR] OpenSSL does not support ML-DSA-44!"
    echo "        Requires OpenSSL 3.5+ with post-quantum support."
    exit 1
fi
echo "[OK] OpenSSL $(openssl version | cut -d' ' -f2) with ML-DSA-44 support"
echo ""

# Clean up old files
echo "[CLEAN] Removing old certificate files..."
rm -f ca_cert.pem ca_key.pem 2>/dev/null || true
rm -f client_cert.pem server_cert.pem 2>/dev/null || true
rm -f client_key.h server_key.h 2>/dev/null || true
rm -f ca_cert.h client_cert.h server_cert.h 2>/dev/null || true
rm -f convert_pem_to_header.py 2>/dev/null || true
rm -f *.der 2>/dev/null || true
echo "[OK] Old files removed"
echo ""

# =============================================================================
# Generate ML-DSA-44 Private Keys
# =============================================================================
echo "[KEYGEN] Generating ML-DSA-44 private keys..."

echo "  -> Generating client private key..."
openssl genpkey -algorithm ML-DSA-44 -out client_key.pem
echo "  -> Generating server private key..."
openssl genpkey -algorithm ML-DSA-44 -out server_key.pem

echo "[OK] Private keys generated"
echo ""

# =============================================================================
# Extract Public Keys in SubjectPublicKeyInfo DER format
# =============================================================================
echo "[EXTRACT] Extracting public keys (SubjectPublicKeyInfo DER)..."

echo "  -> Extracting client public key..."
openssl pkey -in client_key.pem -pubout -outform DER -out client_pubkey.der

echo "  -> Extracting server public key..."
openssl pkey -in server_key.pem -pubout -outform DER -out server_pubkey.der

echo "[OK] Public keys extracted"
echo ""

# =============================================================================
# Convert Private Keys to DER format
# =============================================================================
echo "[CONVERT] Converting private keys to DER format..."

openssl pkey -in client_key.pem -outform DER -out client_key.der
openssl pkey -in server_key.pem -outform DER -out server_key.der

echo "[OK] Private keys converted to DER"
echo ""

# =============================================================================
# Function to convert binary to C array
# =============================================================================
bin_to_c_array() {
    local input_file="$1"
    local array_name="$2"
    local output_file="$3"
    local append="$4"
    
    local size=$(wc -c < "$input_file")
    
    if [ "$append" = "append" ]; then
        echo "" >> "$output_file"
    fi
    
    echo "static const unsigned char ${array_name}[] = {" >> "$output_file"
    xxd -i < "$input_file" | sed 's/^/  /' >> "$output_file"
    echo "};" >> "$output_file"
    echo "static const int ${array_name}_len = sizeof(${array_name});" >> "$output_file"
}

# =============================================================================
# Generate Client RPK Header (client's private key + server's public key)
# =============================================================================
echo "[HEADER] Generating client_rpk.h..."

cat > client_rpk.h << 'EOF'
/*
 * client_rpk.h - Client Raw Public Key Authentication Data
 * 
 * Generated by generate_rpk_keys.sh
 * Algorithm: ML-DSA-44 (NIST FIPS 204)
 * 
 * Contains:
 *   - client_key_der[]     : Our private key for signing
 *   - server_pubkey_der[]  : Server's public key for verification
 */

#ifndef CLIENT_RPK_H
#define CLIENT_RPK_H

/* Client's ML-DSA-44 Private Key (for signing during handshake) */
EOF

bin_to_c_array "client_key.der" "client_key_der" "client_rpk.h" "append"

cat >> client_rpk.h << 'EOF'

/* Server's ML-DSA-44 Public Key (for verifying server's RPK) */
EOF

bin_to_c_array "server_pubkey.der" "server_pubkey_der" "client_rpk.h" "append"

cat >> client_rpk.h << 'EOF'

/* Client's ML-DSA-44 Public Key (sent as our RPK) */
EOF

bin_to_c_array "client_pubkey.der" "client_pubkey_der" "client_rpk.h" "append"

echo "" >> client_rpk.h
echo "#endif /* CLIENT_RPK_H */" >> client_rpk.h

echo "[OK] client_rpk.h generated"

# =============================================================================
# Generate Server RPK Header (server's private key + client's public key)
# =============================================================================
echo "[HEADER] Generating server_rpk.h..."

cat > server_rpk.h << 'EOF'
/*
 * server_rpk.h - Server Raw Public Key Authentication Data
 * 
 * Generated by generate_rpk_keys.sh
 * Algorithm: ML-DSA-44 (NIST FIPS 204)
 * 
 * Contains:
 *   - server_key_der[]     : Our private key for signing
 *   - client_pubkey_der[]  : Client's public key for verification
 */

#ifndef SERVER_RPK_H
#define SERVER_RPK_H

/* Server's ML-DSA-44 Private Key (for signing during handshake) */
EOF

bin_to_c_array "server_key.der" "server_key_der" "server_rpk.h" "append"

cat >> server_rpk.h << 'EOF'

/* Client's ML-DSA-44 Public Key (for verifying client's RPK) */
EOF

bin_to_c_array "client_pubkey.der" "client_pubkey_der" "server_rpk.h" "append"

cat >> server_rpk.h << 'EOF'

/* Server's ML-DSA-44 Public Key (sent as our RPK) */
EOF

bin_to_c_array "server_pubkey.der" "server_pubkey_der" "server_rpk.h" "append"

echo "" >> server_rpk.h
echo "#endif /* SERVER_RPK_H */" >> server_rpk.h

echo "[OK] server_rpk.h generated"
echo ""

# =============================================================================
# Summary
# =============================================================================
echo "============================================================================="
echo "                           GENERATION COMPLETE"
echo "============================================================================="
echo ""
echo "Generated files:"
echo "  Private Keys (PEM):"
echo "    - client_key.pem      : $(wc -c < client_key.pem) bytes"
echo "    - server_key.pem      : $(wc -c < server_key.pem) bytes"
echo ""
echo "  Private Keys (DER):"
echo "    - client_key.der      : $(wc -c < client_key.der) bytes"
echo "    - server_key.der      : $(wc -c < server_key.der) bytes"
echo ""
echo "  Public Keys (DER - SubjectPublicKeyInfo):"
echo "    - client_pubkey.der   : $(wc -c < client_pubkey.der) bytes"
echo "    - server_pubkey.der   : $(wc -c < server_pubkey.der) bytes"
echo ""
echo "  C Headers for Embedded Use:"
echo "    - client_rpk.h        : Client private key + server public key"
echo "    - server_rpk.h        : Server private key + client public key"
echo ""
echo "Usage:"
echo "  Client (boot/): #include \"../certs/client_rpk.h\""
echo "  Server:         #include \"../certs/server_rpk.h\" or copy to server/"
echo ""
echo "============================================================================="

# Cleanup intermediate DER files (optional - comment out to keep)
# rm -f client_key.der server_key.der
