// Real ML-DSA-44 certificates - generated by generate_ml_dsa_certs.sh
// Algorithm: ML-DSA-44 (NIST FIPS 204)
// Validity: 1 year
// Organization: QTrino Labs

#include "../certs/ca_cert.h"
#include "../certs/client_cert.h"
#include "../certs/client_key.h"
